"use server";

export async function getRegions() {
  return [
    { code: "BE", name: "Belgium" },
    { code: "BG", name: "Bulgaria" },
    { code: "CH", name: "Switzerland" },
    { code: "CZ", name: "Czech Republic" },
    { code: "DE-LU", name: "Germany, Luxembourg" },
    { code: "DE-AT-LU", name: "Germany, Austria, Luxembourg" },
    { code: "DK1", name: "Denmark 1" },
    { code: "DK2", name: "Denmark 2" },
    { code: "EE", name: "Estonia" },
    { code: "ES", name: "Spain" },
    { code: "FI", name: "Finland" },
    { code: "FR", name: "France" },
    { code: "GR", name: "Greece" },
    { code: "HR", name: "Croatia" },
    { code: "HU", name: "Hungary" },
    { code: "IT-Calabria", name: "Italy Calabria" },
    { code: "IT-Centre-North", name: "Italy Centre North" },
    { code: "IT-Centre-South", name: "Italy Centre South" },
    { code: "IT-North", name: "Italy North" },
    { code: "IT-SACOAC", name: "Italy Sardinia Corsica AC" },
    { code: "IT-SACODC", name: "Italy Sardinia Corsica DC" },
    { code: "IT-Sardinia", name: "Italy Sardinia" },
    { code: "IT-Sicily", name: "Italy Sicily" },
    { code: "IT-South", name: "Italy South" },
    { code: "LT", name: "Lithuania" },
    { code: "LV", name: "Latvia" },
    { code: "ME", name: "Montenegro" },
    { code: "NL", name: "Netherlands" },
    { code: "NO1", name: "Norway 1" },
    { code: "NO2", name: "Norway 2" },
    { code: "NO2NSL", name: "Norway North Sea Link" },
    { code: "NO3", name: "Norway 3" },
    { code: "NO4", name: "Norway 4" },
    { code: "NO5", name: "Norway 5" },
    { code: "PL", name: "Poland" },
    { code: "PT", name: "Portugal" },
    { code: "RO", name: "Romania" },
    { code: "RS", name: "Serbia" },
    { code: "SE1", name: "Sweden 1" },
    { code: "SE2", name: "Sweden 2" },
    { code: "SE3", name: "Sweden 3" },
    { code: "SE4", name: "Sweden 4" },
    { code: "SI", name: "Slovenia" },
    { code: "SK", name: "Slovakia" },
  ];
}
