export const biddingZones = {
  BE: "Belgium",
  BG: "Bulgaria",
  CH: "Switzerland",
  CZ: "Czech Republic",
  "DE-LU": "Germany, Luxembourg",
  "DE-AT-LU": "Germany, Austria, Luxembourg",
  DK1: "Denmark 1",
  DK2: "Denmark 2",
  EE: "Estonia",
  ES: "Spain",
  FI: "Finland",
  FR: "France",
  GR: "Greece",
  HR: "Croatia",
  HU: "Hungary",
  "IT-Calabria": "Italy Calabria",
  "IT-Centre-North": "Italy Centre North",
  "IT-Centre-South": "Italy Centre South",
  "IT-North": "Italy North",
  "IT-SACOAC": "Italy Sardinia Corsica AC",
  "IT-SACODC": "Italy Sardinia Corsica DC",
  "IT-Sardinia": "Italy Sardinia",
  "IT-Sicily": "Italy Sicily",
  "IT-South": "Italy South",
  LT: "Lithuania",
  LV: "Latvia",
  ME: "Montenegro",
  NL: "Netherlands",
  NO1: "Norway 1",
  NO2: "Norway 2",
  NO2NSL: "Norway North Sea Link",
  NO3: "Norway 3",
  NO4: "Norway 4",
  NO5: "Norway 5",
  PL: "Poland",
  PT: "Portugal",
  RO: "Romania",
  RS: "Serbia",
  SE1: "Sweden 1",
  SE2: "Sweden 2",
  SE3: "Sweden 3",
  SE4: "Sweden 4",
  SI: "Slovenia",
  SK: "Slovakia",
};
